
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Noto_Sans } from 'next/font/google'

const notoSans = Noto_Sans({ subsets: ["latin"], weight: ["200", "300", "400", "700", "800"] })

export const metadata: Metadata = {
  title: 'Chat test app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      <head>
      </head>
      <body className={notoSans.className}>
        {children}
      </body>
    </html>
  )
}
